swagger: "2.0"
info:
   title: Bank Argent API documentation
   description: Contains all available API endpoints in this codebase
   version: "1.0.0"
   termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
   - http
paths:
   /user/{id}/accounts:
      get:
         summary: Get accounts
         description: API to retrieve all accounts available
         parameters:
            - in: path
              name: id
              description: User ID
              required: true
              type: integer
         responses:
            "200":
               description: Get accounts successfully
               schema:
                  $ref: "#/definitions/GetAccounts"
            "400":
               description: Invalid Fields
            "401":
               description: Unauthorized
            "500":
               description: Internal Server Error
   /accounts/{account_id}/transactions:
      get:
         summary: Get transactions for a specific account
         description: API to retrieve transactions for a specific account
         parameters:
            - in: path
              name: user_id
              description: User ID
              required: true
              type: integer
            - in: path
              name: account_id
              description: Account ID
              required: true
              type: integer
         responses:
            "200":
               description: Get transactions successfully
               schema:
                  $ref: "#/definitions/GetTransactions"
            "400":
               description: Invalid Fields
            "401":
               description: Unauthorized
            "500":
               description: Internal Server Error
   /accounts/{account_id}/transactions/{transaction_id}:
      put:
         summary: Update transaction note
         description: API to update the note of a specific transaction
         parameters:
            - in: path
              name: user_id
              description: User ID
              required: true
              type: integer
            - in: path
              name: account_id
              description: Account ID
              required: true
              type: integer
            - in: path
              name: transaction_id
              description: Transaction ID
              required: true
              type: integer
            - in: body
              name: transactionNote
              description: New note for the transaction
              required: true
              schema:
                 type: object
                 properties:
                    note:
                       type: string
         responses:
            "200":
               description: Transaction note updated successfully
            "400":
               description: Invalid Fields
            "401":
               description: Unauthorized
            "500":
               description: Internal Server Error
definitions:
   GetAccounts:
      type: object
      properties:
         accounts:
            type: array
            items:
               $ref: "#/definitions/Account"
   Account:
      type: object
      properties:
         id:
            type: integer
         accountType:
            type: string
         balance:
            type: number
   GetTransactions:
      type: object
      properties:
         transactions:
            type: array
            items:
               $ref: "#/definitions/Transaction"
   Transaction:
      type: object
      properties:
         id:
            type: integer
         description:
            type: string
         amount:
            type: number
         date:
            type: string
         balance:
            type: number
         transactionType:
            type: string
         category:
            type: string
         note:
            type: string
